### ISSUE TITLE
Unable to load the requested language file: language/malay/form_validation_lang.php

### ISSUE THREAD

**Issue by Ahblisk** [opensourcepos/upptime#303]
**Describe the bug**
After logging into the initial demo page, I am immediately presented with an error screen stating:
 "
An Error Was Encountered

Unable to load the requested language file: language/malay/form_validation_lang.php
"

**To Reproduce**
1. Go to '[the demo](https://demo.opensourcepos.org/)'
2. Log in with the demo credentials
3. See error

**Expected behavior**
I expected to be presented with the POS site.

**Screenshots**
![image](https://user-images.githubusercontent.com/60359943/197636954-85352a88-b655-43af-b204-cd8f64e2944b.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser [firefox]
 - Version [105.0.3]

**Comment by jekkos** [comment]
Resolved now
